name: GitHub Pages Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0 # for use of git describe

      - name: Install Packages
        run: sudo apt install -y gcc g++ make cmake graphviz doxygen git

      - name: Build Documentation
        run: mkdir build && cd build && cmake .. && make docs

      - name: Deploy GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/docs/html
          publish_branch: gh-pages
